In [1]:
import numpy as np

In [5]:
# 生成相关矩阵
temp=[[1,2,3],[1,2,3]]
data1=np.array(temp,dtype=np.float32)
print(data1)
# np.array(object, dtype=None)
# object: 列表、元组或 Pandas 的 Series。
# dtype: 数据类型（常用 np.float32）。

# np.zeros((rows, cols)): 创建全 0 矩阵（初始化参数常用）。
data2=np.zeros((2,3))
print(data2)
# np.ones((rows, cols)): 创建全 1 矩阵。
data3=np.ones((2,3))
print(data3)
# np.linspace(start, stop, num): 在一段范围内生成等差数列（画拟合曲线时常用）。
data3=np.linspace(1,10,10)
print(data3)

[[1. 2. 3.]
 [1. 2. 3.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [8]:
data=data.reshape((1,6))
print(data)
data=data.reshape((-1,1))
print(data)
# array.reshape(new_shape)
# new_shape: 一个元组，如 (97, 1)。
# 特殊值 -1：代表“自动计算”。比如 reshape(-1, 1) 表示：我不管有多少行，但我只要它是 1 列，行数你帮我算。

[[1. 2. 3. 1. 2. 3.]]
[[1.]
 [2.]
 [3.]
 [1.]
 [2.]
 [3.]]


In [9]:
data_answer=data@(data.reshape((1,-1)))# 
print(data_answer)

[[1. 2. 3. 1. 2. 3.]
 [2. 4. 6. 2. 4. 6.]
 [3. 6. 9. 3. 6. 9.]
 [1. 2. 3. 1. 2. 3.]
 [2. 4. 6. 2. 4. 6.]
 [3. 6. 9. 3. 6. 9.]]


In [14]:
print(data1.sum(axis=1))
#array.sum(axis=None)/mean用法相同
print(data1.sum(axis=0))

[6. 6.]
[2. 4. 6.]
