In [1]:
import torch
import numpy as np

In [2]:
##张量的初始化##
##           ##

data=[[1,2],[3,4]]
X_data=torch.tensor(data)
print(f"由数据直接转化\n{X_data}")

由数据直接转化
tensor([[1, 2],
        [3, 4]])


In [3]:
data_np=np.array(data)
X_np=torch.from_numpy(data_np)
print(f"由numpy转化\n{X_data}")

由numpy转化
tensor([[1, 2],
        [3, 4]])


In [4]:
X_ones=torch.ones_like(X_data)#保留参数张量的性质（形状、数据类型）
X_rand=torch.rand_like(X_data,dtype=torch.float32)#复刻形状，填充随机
print(f"由ones_like转化\n{X_ones}")
print(f"由rand_like转化\n{X_rand}")

由ones_like转化
tensor([[1, 1],
        [1, 1]])
由rand_like转化
tensor([[0.8283, 0.8052],
        [0.3771, 0.7461]])


In [5]:
shape=(2,3,)
rand_tensor=torch.rand(shape)
ones_tensor=torch.ones(shape)
zeros_tensor=torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")# 这些的

Random Tensor: 
 tensor([[0.2897, 0.2701, 0.5387],
        [0.8662, 0.2067, 0.0253]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
##张量的属性##
##         ##

tensor=torch.rand((3,4,))
print(tensor)

tensor([[0.8522, 0.0437, 0.3835, 0.4874],
        [0.8569, 0.0810, 0.6646, 0.6787],
        [0.1278, 0.6861, 0.2637, 0.0874]])


In [7]:
print(f"张量的shape:  {tensor.shape}")
print(f"张量的dtype:  {tensor.dtype}")
print(f"张量的device: {tensor.device}")#参与同一个运算（比如加法、矩阵乘法）的所有张量，必须位于同一个 device 上。CPU与GPU

张量的shape:  torch.Size([3, 4])
张量的dtype:  torch.float32
张量的device: cpu


In [8]:
# API (Application Programming Interface，应用程序编程接口)
# 标准库 API：比如 std::vector::push_back()。
# 你调用它，它帮你把数据存进内存。你不需要管它是怎么重新分配内存（realloc）或者处理指针偏移的。push_back 就是 std::vector 给你的 API。
# 系统 API (Windows API / POSIX)：比如 CreateFile() 或 open()。
# 这是操作系统给你的接口。你调用它，硬盘就开始转动读数据。

In [9]:
test=[[1,2,3],
      [4,5,6],
      [7,8,9]]
tensor_test=torch.tensor(test,dtype=torch.float32)
print(tensor_test)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [13]:
print(f"fisrt row:{tensor_test[0]}")
print(f"fisrt col:{tensor_test[:,0]}")
print(f"last row:{tensor_test[-1:,:]}")
tensor_test[1]=0;# 循环填充，不是运用了广播机制
print(tensor_test)

fisrt row:tensor([1., 2., 3.])
fisrt col:tensor([1., 4., 7.])
last row:tensor([[7., 8., 9.]])
tensor([[1., 2., 3.],
        [0., 0., 0.],
        [7., 8., 9.]])


In [18]:
# 还可以进行连接
t1=torch.cat([tensor_test,tensor_test,tensor_test],dim=1)
print(t1)
t2=torch.cat([tensor_test,tensor_test,tensor_test],dim=0)
print(t2)
# t3=torch.cat([tensor_test,ones_tensor],dim=1)
# RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 3 but got size 2 for tensor number 1 in the list.
# print(t3)不能进行大小不合适的张量的叠加

tensor([[1., 2., 3., 1., 2., 3., 1., 2., 3.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [7., 8., 9., 7., 8., 9., 7., 8., 9.]])
tensor([[1., 2., 3.],
        [0., 0., 0.],
        [7., 8., 9.],
        [1., 2., 3.],
        [0., 0., 0.],
        [7., 8., 9.],
        [1., 2., 3.],
        [0., 0., 0.],
        [7., 8., 9.]])


In [20]:
y=torch.ones((1,10))
print(y)
# 矩阵乘法
y1=y@y.T
y2=y.matmul(y.T)
y3=torch.rand_like(y1)
torch.matmul(y,y.T,out=y3)
print(y1)
print(y3)
print(y2)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[10.]])
tensor([[10.]])
tensor([[10.]])


In [23]:
# 将每个元素平方
z=torch.tensor(test,dtype=torch.float32)
z1=z*z
z2=z.mul(z)
z3=torch.rand_like(z1)
torch.mul(z,z,out=z3)
print(z1)
print(z2)
print(z3)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])


In [25]:
# 单元张量如果你有一个单元素张量，比如通过聚合所有 将张量的值转换为一个值，你可以将其转换为 Python 数值使用：item()
sum1=tensor_test.sum()
sum_py=sum1.item()
print(sum_py,type(sum_py))

30.0 <class 'float'>


In [26]:
# 原位操作
print(f"{tensor_test} \n")
tensor_test.add_(5)# 这里运用了广播原理
# 这里运用了广播机制：当你尝试对两个形状不一样的张量进行数学运算（加减乘除）时，PyTorch 会尝试自动“扩张”较小的张量，使它们的形状匹配。

# 底层是如何“对齐内存”的？
# 这是最神奇的地方：PyTorch 并不会真的复制 3 份 5 来浪费内存。
# 在底层 C++ 实现中，它修改了张量的 步长 (Stride)
# 对于那个标量 5，PyTorch 告诉计算内核：“你的步长是 0”。
# 这意味着无论循环跑到第几个元素，指针在内存中永远停留在 5 的位置。
# 结果：在不消耗额外显存的情况下，实现了一个“虚拟”的大张量。
# 3. 广播的两条铁律
# 不是任何两个张量都能广播，必须满足以下条件之一：
# 列数相同
# 有一个行数大小是 1
print(tensor_test)

tensor([[1., 2., 3.],
        [0., 0., 0.],
        [7., 8., 9.]]) 

tensor([[ 6.,  7.,  8.],
        [ 5.,  5.,  5.],
        [12., 13., 14.]])


In [27]:
# 与NumPy的桥接
# CPU 和 NumPy 阵列上的张量可以共享它们底层内存 地点，改变一个地点会改变另一个

In [29]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [30]:
n = np.ones(5)
t = torch.from_numpy(n)
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")# 相互作用

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
